# this file uses prebuilt image in dockerhub
services:
  jekyll:
    image: amirpourmand/al-folio:slim
    #build: .
    ports:
      - 127.0.0.1:8080-8099:8080
      - 127.0.0.1:35729:35729
    volumes:
      - .:/srv/jekyll
    environment:
      - JEKYLL_ENV=development